### ISSUE TITLE
ID3.0.6: I want to be able to see a list view of my side notes after the medical history entry finalized.

### ISSUE THREAD

**Issue by mack1070101** [CMPUT401/ahasServer#36]
- Description/Details:
     After two hours of opening the notes, I need the notes to auto finalize it so that no one is able to tamper with any of the information inside. The only thing that I'll be able to do is print the sheet. 
Tests:
	- Try editing the entry before it is finalized
	- Try editing the entry after it is finalized

**Comment by mack1070101** [comment]
This might already me done. Can the medical record people chime in? @knewbury01 @justinbarclay

**Comment by knewbury01** [comment]
if side notes means follow up notes then for sure done as per kristy, if side notes means notes added after editable duration of medical record, this should also be done as per eric
