### ISSUE TITLE
ID8.0.0: I want to be able to invite users to create an account 

### ISSUE THREAD

**Issue by mack1070101** [CMPUT401/ahasServer#37]
- Description/Details: 
   As a user with admin privileges I want to be able to invite people to create an account on our system. 

Tests: 
        - try inviting someone

**Comment by justinbarclay** [comment]
Need to figure out how to email

**Comment by justinbarclay** [comment]
Should not have closed

**Comment by justinbarclay** [comment]
Implemented and tested on backend
