### ISSUE TITLE
ID8.1.1: I want to be able to delete volunteers from our system.

### ISSUE THREAD

**Issue by mack1070101** [CMPUT401/ahasServer#40]
- Description/Details: 
   As a user with admin privileges I want to be able to remove old contacts, if a person no longer volunteers with ahas. 

Tests: 
        - try deleting volunteer

**Comment by knewbury01** [comment]
for the front end this will probably be as simple as adding a delete button to the currently existing edit contact page.
The larger less easy part is adding the admin privilege to let us access the edit contacts page even.

**Comment by justinbarclay** [comment]
backend is done
