### ISSUE TITLE
add techs to contact types

### ISSUE THREAD

**Issue by knewbury01** [CMPUT401/ahasServer#53]
done, but . want to find an ideal arrangement for UI. 
potential solutions: 
leave it as four headings across. kinda not the best>though maybe not actually that bad?
mayeb put it into different tabs within the page, one for each and then one for all in one list
put three across and one a bit below. actually like this the least... but kinda like retaining the ability to see all of them at one time and still sorted by type.

**Comment by knewbury01** [comment]
one note, not quite related to this but sorta. 

error messages when creating contact from server come back mildly off, 

ex empty address returns : Address Address is required. should be Address is required

anyways the idea is we wont even get that far cuz front end checks.

**Comment by knewbury01** [comment]
oh. also apparently the technician type for volunteer is not currently supported on back end. 

The error message returned for this also contains a minor issue. Laboratory is misspelt. comes back as Labratory.

**Comment by mack1070101** [comment]
Back end is done, Send "Technician" as a valid type
