### ISSUE TITLE
Split address input into 3 lines

### ISSUE THREAD

**Issue by MarcOlivierLajeunesse** [CMPUT401/ahasServer#56]

**Comment by knewbury01** [comment]
just for clarity sake , this needs to be split into three on the backend for both contacts and clients

**Comment by mack1070101** [comment]
@MarcOlivierLajeunesse  is this for clients?

**Comment by MarcOlivierLajeunesse** [comment]
clients and contacts. Anything with an address as an input. This has to be done for GET, PUT, and POST requests.

**Comment by mack1070101** [comment]
Clients is done, docs to follow later. Note alternative Contact address has been split into 3 lines as well

**Comment by mack1070101** [comment]
Contacts is done, docs to follow later

**Comment by mack1070101** [comment]
Backend complete, documents written

**Comment by knewbury01** [comment]
front end complete everywhere
