### ISSUE TITLE
fixes on medical record updating

### ISSUE THREAD

**Issue by knewbury01** [CMPUT401/ahasServer#57]
medications of medical records still do not update.

one question. if I add a new medication it is easier for me to gather all meds in one step, but then in order to do so I will have to attach an id to those, but it will be undefined. that seems nonideal, so what do I send in that field?

Situtations to consider (that do not work):

adding a new medication to the medication list. front end can verify that I am sending the new one, but it is not sent back.

deleting one medication from the list. how did we want to do this. I can send back a valid field in all medications? simply omitting it from the list of what I am sending back is not enough? or?

Situations that we are all good on currently :

Altering a preexisting medication works just fine.

**Comment by knewbury01** [comment]
now looks like adding new ones works, yay!

still need to do deletion, still havent discussed what the front end needs to send to allow for this to occur.

**Comment by mack1070101** [comment]
Back end now supports deletion for medications. Send HTTP DELETE to
"/api/patients/#{@patient.id}/medications/{medication.id}"

**Comment by mack1070101** [comment]
Not sure how to document this in API documentation

**Comment by knewbury01** [comment]
confirmed on front end
