### ISSUE TITLE
update search functions. 

### ISSUE THREAD

**Issue by MarcOlivierLajeunesse** [CMPUT401/ahasServer#60]
Kristy updated the search function (i think in contacts). The update must be applied to client and patient searches.

**Comment by MarcOlivierLajeunesse** [comment]
client search is done.

**Comment by MarcOlivierLajeunesse** [comment]
Client search still needs to search on enter press. move search button to the side.

**Comment by MarcOlivierLajeunesse** [comment]
search updated for client search. also updated the styling for client and patient lists to match that of the admin page.

**Comment by erichsueh** [comment]
patient search now matches client search
